config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token

  get "up" => "rails/health#show", as: :rails_health_check

  root        to: "site/welcome#index"
  get "home", to: "site/welcome#index"

  get  "companies/signup", to: "companies/signup#new"
  post "companies/signup", to: "companies/signup#create"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
# typed: false
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password

  validates :email_address,         presence: true, uniqueness: true, email: { message: "deve ter um formato válido" }
  validates :password,              presence: true, length: { minimum: 8 }, password: true
  validates :password_confirmation, presence: true
  validates :role,                  presence: true, inclusion: { in: -> { User.roles.keys } }

  has_many :sessions, dependent: :destroy

  enum :role, { admin: 0, company: 1, applicant: 2 }

  after_initialize :set_default_role, if: :new_record?

  private

  def set_default_role
    self.role ||= :applicant
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/companies/signup_controller.rb
# typed: false
# frozen_string_literal: true

class Companies::SignupController < CompaniesController
  allow_unauthenticated_access only: [ :new, :create ]

  include UserRegistrable

  def new
    new_user
  end

  def create
    create_user
  end
end

app/controllers/companies_controller.rb
# typed: false
# frozen_string_literal: true

class CompaniesController < ApplicationController
  layout "companies"
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      resume_session
    end

    def require_authentication
      resume_session || request_authentication
    end


    def resume_session
      Current.session ||= find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id])
    end


    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to new_session_path
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || root_url
    end


    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
      end
    end

    def terminate_session
      Current.session.destroy
      cookies.delete(:session_id)
    end
end

app/controllers/concerns/user_registrable.rb
module UserRegistrable
  extend ActiveSupport::Concern

  included do
    def new_user
      @user = User.new
    end

    def create_user
      @user = User.new(user_params)
      if @user.save
        redirect_to root_path flash[:success] = "Cadastro realizado com sucesso!"
      else
        flash.now[:error] = "Verifique os campos em vermelho!"
        render :new, status: :unprocessable_entity
      end
    end

    private

    def user_params
      params.require(:user).permit(:email_address, :password, :password_confirmation, :role)
    end
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]

  def new
  end

  def create
    if user = User.find_by(email_address: params[:email_address])
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to new_session_path, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      redirect_to new_session_path, notice: "Password has been reset."
    else
      redirect_to edit_password_path(params[:token]), alert: "Passwords did not match."
    end
  end

  private
    def set_user_by_token
      @user = User.find_by_password_reset_token!(params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to new_password_path, alert: "Password reset link is invalid or has expired."
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Tente novamente mais tarde." }

  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email_address, :password))
      start_new_session_for user
      redirect_to after_authentication_url
    else
      redirect_to new_session_path, alert: "Email ou senha incorretos."
    end
  end

  def destroy
    terminate_session
    redirect_to new_session_path
  end
end

app/controllers/site/welcome_controller.rb
# typed: false
# frozen_string_literal: true

class Site::WelcomeController < SiteController
  def index; end
end

app/controllers/site_controller.rb
# typed: false
# frozen_string_literal: true

class SiteController < ApplicationController
  allow_unauthenticated_access only: [ :index ]

  layout "site"
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/companies/signup/new.html.erb
<section>
  <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
    <div class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
      <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
        <h1 class="text-xl text-center font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
          Criar conta
        </h1>
        <%= simple_form_for(@user, url: companies_signup_path, local: true, html: { class: 'space-y-4 md:space-y-6' }) do |form| %>
          <div>
            <%= form.input :email_address, 
              label_html: { class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white"},
              autofocus: true,
              input_html: { autocomplete: "email", class: "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" },
              placeholder: t('placeholders.email') %>
          </div>
          <div>
            <%= form.input :password,
            label_html: { class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white"},
            input_html: { autocomplete: "new-password", class: "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" },
            placeholder: t('placeholders.minimum_characters') %>
          </div>
          <div>
            <%= form.input :password_confirmation,
            label_html: { class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white"},
            input_html: { autocomplete: "new-password", class: "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" },
            placeholder: t('placeholders.repeat_password') %>
          </div>
          <%= form.input :role, as: :hidden, input_html: { value: "company" } %>
          <%= form.submit 'Cadastrar', class: "w-full text-white bg-green-600 hover:bg-green-700 focus:ring-4 focus:outline-none focus:ring-green-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Talentari" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/companies.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Talentari" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/site.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Talentari" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_public_navbar.html.erb
<nav class="border-b-3 bg-blue-600 border-emerald-600">
  <div class="container px-4 py-3 mx-auto flex justify-between items-center">
    <div>
      <h1 class="font-bold text-white text-xl">Talentari</h1>
    </div>
    <ul>
      <li>
        <%= link_to "Entrar", new_session_path, class: "block bg-green-300 py-2 px-4 text-blue-900 rounded" %>
      </li>
    </ul>
  </div>
</nav>  

app/views/site/index.html.erb
<%= render "shared/public_navbar" %>

<section class="bg-gray-50">
  <div class="mx-auto max-w-screen-xl px-4 py-32 lg:flex lg:h-screen lg:items-center">
    <div class="mx-auto max-w-xl text-center">
      <h1 class="text-3xl text-blue-950 font-extrabold sm:text-5xl">
        Encontre talentos. Vagas incríveis.
      </h1>
      <p class="mt-4 text-zinc-900 sm:text-xl/relaxed">
         Candidata é a plataforma ideal para conectar recrutadores e candidatos. Com nossas ferramentas, você pode encontrar oportunidades de emprego que correspondam às suas habilidades e experiências, ou encontrar os melhores talentos para sua empresa.
      </p>
      <div class="mt-8 flex flex-wrap justify-center gap-4">
        <%= link_to companies_signup_path, class: "block w-full rounded bg-emerald-600 px-12 py-3 text-sm font-medium text-white shadow hover:bg-emerald-700 focus:outline-none focus:ring active:bg-emerald-500 sm:w-auto" do %>
          Quero contratar
        <% end %>
        <a
          class="block w-full rounded px-12 py-3 text-sm font-medium text-emerald-600 shadow hover:text-emerald-700 focus:outline-none focus:ring active:text-emerald-500 sm:w-auto"
          href="#">
          Quero trabalhar
        </a>
      </div>
    </div>
  </div>
</section>